/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HeaderSnackBar: typeof import('./src/components/headerSnackBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TypingEffect: typeof import('./src/components/TypingEffect.vue')['default']
    UpLoadFile: typeof import('./src/components/UpLoadFile.vue')['default']
  }
}
