version: '3'
services:
  easyai-nginx-frontend:
    container_name: easyai-nginx-frontend
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/html/dist:/home/easyai/projects/easyai-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
